apiVersion: v2
name: kafka
description: Kafka dependency for RabbitOS Enterprise
type: application
version: 1.0.0
dependencies:
  - name: kafka
    version: "26.x.x"
    repository: https://charts.bitnami.com/bitnami
