apiVersion: 1

datasources:
  - name: RabbitOS-Postgres
    type: postgres
    url: ${SUPABASE_DB_HOST}:5432
    database: postgres
    user: ${SUPABASE_DB_USER}
    secureJsonData:
      password: ${SUPABASE_DB_PASSWORD}
    jsonData:
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
